version: "3.8"
services:
    test-db:
        image: postgres:15.1-alpine
        ports:
            - 5434:5432
        environment:
            - POSTGRES_USER=rootuser
            - POSTGRES_PASSWORD=rootpass
            - POSTGRES_DB=testing